# development:
#   adapter: postgresql
#   encoding: unicode
#   database: task_process
#   pool: 2
#   username: santiago
#   password: your_password

# production:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   host: <%= ENV['DATABASE_HOST'] %>
#   database: <%= ENV['DATABASE_NAME'] %>
#   username: <%= ENV['DATABASE_USER'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  adapter: sqlite3
  database: database.db

test:
  adapter: sqlite3
  database: database.db

production:
  adapter: postgresql
  host: localhost
  url: <%= ENV["DATABASE_URL"] %>